export type CalibrationData={
    id:string
}
export enum Free3DWebSocketEvents {
    UPDATE_CALIBRATION = "UPDATE_CALIBRATION", On_UPDATE_CALIBRATION = "On_UPDATE_CALIBRATION", SET_CALIBRATION = "SET_CALIBRATION", ON_SET_CALIBRATION = "ON_SET_CALIBRATION", GET_CALIBRATION = "GET_CALIBRATION"
}